# Generated by Django 3.2.7 on 2022-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bustitle', models.CharField(max_length=150)),
                ('seat_id', models.CharField(max_length=150)),
                ('passenger_firstname', models.CharField(max_length=150)),
                ('passenger_lastname', models.CharField(max_length=150)),
                ('noof_paasenger', models.CharField(max_length=150)),
                ('startingpoint', models.CharField(max_length=150)),
                ('endingpoint', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='busdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bustitle', models.CharField(max_length=150)),
                ('type_id', models.CharField(max_length=150)),
                ('registerno', models.CharField(max_length=150)),
                ('makeyear', models.CharField(max_length=150)),
                ('busstation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='bustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bustitle', models.CharField(max_length=150)),
                ('startingpoint', models.CharField(max_length=150)),
                ('endingpoint', models.CharField(max_length=150)),
                ('amountperseat', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bustitle', models.CharField(max_length=150)),
                ('passenger_firstname', models.CharField(max_length=150)),
                ('noof_paasenger', models.CharField(max_length=150)),
                ('payment_type', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('cardno', models.CharField(max_length=150)),
                ('ccvno', models.CharField(max_length=150)),
                ('expdate', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingpoint', models.CharField(max_length=150)),
                ('endingpoint', models.CharField(max_length=150)),
                ('busname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatnumber', models.CharField(max_length=150)),
                ('bus_id', models.CharField(max_length=150)),
                ('bus_name', models.CharField(blank=True, max_length=150)),
                ('seatstatus', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=150)),
                ('trip_id', models.CharField(max_length=150)),
                ('arrivingtime', models.CharField(max_length=150)),
                ('departuretime', models.CharField(max_length=150)),
                ('bus_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripname', models.CharField(max_length=150)),
                ('busname', models.CharField(max_length=150)),
                ('startingstop', models.CharField(max_length=150)),
                ('endingstop', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
            ],
        ),
    ]
